# name: Run JESftp Script on Windows

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   run-script:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           # If you have a requirements.txt file, uncomment the next line:
#           # pip install -r requirements.txt

#       - name: Run JESftp.py script
#         run: |
#           python "C:\Windows\actions-jes\JESftp.py" "C:\Windows\actions-jes\JCL"shell:pwsh
#         #working-directory: C:\Windows\
name: Run JESftp Script on Windows
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  run-script:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
 
      - name: Debug List all environment variables
        run: Get-ChildItem Env
        shell: pwsh
 
      - name: Debug List directory contents
        run: dir "C:\Windows\actions-jes"
        shell: pwsh
 
      - name: Debug Print current user
        run: whoami
        shell: pwsh
 
      - name: Debug Check Python version
        run: python --version
        shell: pwsh
 
      - name: Run JESftp.py script
        run: python "C:\Windows\actions-jes\JESftp.py" "C:\Windows\actions-jes\JCL"
        shell: pwsh
